
sonar.projectKey=LearningPlatform_frontend
sonar.projectName=LearningPlatform_frontend
sonar.projectVersion=1.0
sonar.inclusions=src/**
sonar.sources="src"
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**